name: VogueGen Web Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Flutter 3.10.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6

      - name: Checkout Flutter 3.10.7
        shell: bash
        run: |
          cd ${{ env.FLUTTER_ROOT }};
          git fetch --tags;
          git checkout 3.10.7;
          flutter --version;

      - name: Get dependencies
        run: flutter pub get

      - name: Upgrade dependencies
        run: flutter pub upgrade --verbose

      - name: Run tests
        run: flutter test

      - name: Build web app
        run: flutter build web --verbose

      - name: Archive web app
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built web app artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app
          path: build/web
