name: VogueGen Web Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone Flutter repository at specified version
        run: git clone https://github.com/flutter/flutter.git -b 3.20.0-14.0.pre --depth 1 ${{ github.workspace }}/flutter

      - name: Add Flutter to PATH
        run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      - name: Build web app
        run: flutter build web --verbose

      - name: Archive web app
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built web app artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app
          path: build/web
