name: Voguegen Web Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: voguegen-web-app
          path: build/web/
