name: VogueGen Web Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.4.0" # Or use the latest version
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release
