name: Flutter Web CI/CD and Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone Flutter repository at specified version
        run: git clone https://github.com/flutter/flutter.git -b 3.20.0-14.0.pre --depth 1 ${{ github.workspace }}/flutter

      - name: Add Flutter to PATH
        run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      - name: Install Flutter dependencies
        run: flutter doctor

      - name: Install app dependencies
        run: flutter pub get --verbose

      - name: Upgrade dependencies
        run: flutter pub upgrade --verbose

      - name: Build web app
        run: flutter build web --verbose

      - name: Archive web app
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Download built web app artifact
        uses: actions/download-artifact@v2
        with:
          name: web-app
          path: build/web

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
          SOURCE_DIR: "build/web"

      - name: Invalidate CloudFront Distribution
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: "ap-south-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
